/**
 * Base de datos local de perfumes (fallback cuando Firestore no está configurado).
 * Cada producto tiene precio al mayor (precioMayor) y al detal (precioDetal).
 *
 * DETAL_MARKUP: margen (USD) que se suma al precio al mayor para calcular
 * el precio al detal cuando un producto no define precioDetal propio.
 */
const DETAL_MARKUP = 5;

const PERFUMES_RAW = [
  // Casa, Nombre, Precio al mayor (USD) [, Precio al detal opcional]
  ["Afnan", "9 AM Dive", 20],
  ["Afnan", "9 AM Pour Femme", 20],
  ["Afnan", "9 PM Elixir", 20],
  ["Afnan", "9 PM Men", 20],
  ["Afnan", "9 PM Night Out", 25],
  ["Afnan", "9 PM Pour Femme", 20],
  ["Afnan", "9 PM Rebel", 20],
  ["Al Haramain", "Amber Oud Aqua Dubai Edition", 20],
  ["Al Haramain", "Amber Oud Dubai Night", 20],
  ["Al Haramain", "Amber Oud Gold Edition", 20],
  ["Al Haramain", "Amber Oud Ultra Violet", 20],
  ["Antonio Banderas", "Blue Seduction", 18],
  ["Ariana Grande", "Ari", 18],
  ["Ariana Grande", "Cloud", 9],
  ["Ariana Grande", "Cloud Intense", 9],
  ["Ariana Grande", "Cloud Pink", 15],
  ["Ariana Grande", "Mod", 15],
  ["Ariana Grande", "Mod Blush", 15],
  ["Ariana Grande", "REM", 18],
  ["Ariana Grande", "Sweet Like Candy", 18],
  ["Ariana Grande", "Thank U Next", 15],
  ["Ariana Grande", "Thank U Next 2.0", 15],
  ["Armaf", "Caballo", 20],
  ["Armaf", "Club de Nuit Intense Man", 15],
  ["Armaf", "Club de Nuit Lionheart Men", 20],
  ["Armaf", "Club de Nuit Lionheart Woman", 20],
  ["Armaf", "Club de Nuit Oud", 15],
  ["Armaf", "Club de Nuit Milestone", 15],
  ["Armaf", "Club de Nuit Imperiale", 15],
  ["Armaf", "Club de Nuit Sillage", 15],
  ["Armaf", "Club de Nuit Untold", 15],
  ["Armaf", "Club de Nuit Maleka", 15],
  ["Armaf", "Club de Nuit Iconic", 15],
  ["Armaf", "Club de Nuit Urban Man Elixir", 15],
  ["Armaf", "Club de Nuit Woman", 15],
  ["Armaf", "Club de Nuit Precieux", 30],
  ["Armaf", "Island Bliss", 20],
  ["Armaf", "Island Breeze", 20],
  ["Armaf", "Bon Bon", 20],
  ["Armaf", "Odyssey AOUD", 15],
  ["Armaf", "Odyssey Aqua", 20],
  ["Armaf", "Odyssey Artisto", 15],
  ["Armaf", "Odyssey Bahamas", 20],
  ["Armaf", "Odyssey Candee", 15],
  ["Armaf", "Odyssey Dubai Chocolate", 20],
  ["Armaf", "Odyssey Homme", 15],
  ["Armaf", "Odyssey Homme White Edition", 15],
  ["Armaf", "Odyssey Limoni", 20],
  ["Armaf", "Odyssey Mandarin Sky", 20],
  ["Armaf", "Odyssey Mandarin Sky Elixir", 20],
  ["Armaf", "Odyssey Mandarin Sky Vintage", 20],
  ["Armaf", "Odyssey Marshmellow", 20],
  ["Armaf", "Odyssey Mega", 15],
  ["Armaf", "Odyssey Go Mango", 20],
  ["Armaf", "Odyssey Toffee Coffee", 20],
  ["Armaf", "Odyssey Spectra", 15],
  ["Armaf", "Odyssey Eau de Montagne", 20],
  ["Armaf", "Odyssey Tyrant", 15],
  ["Armaf", "Odyssey Wild One", 15],
  ["Armaf", "Yum Yum", 20],
  ["Azzaro", "Azzaro Wanted", 20],
  ["Azzaro", "Azzaro Intense", 20],
  ["Bharara", "Double Bleu", 20],
  ["Bharara", "King", 20],
  ["Bharara", "Niche Femme", 20],
  ["Bharara", "Onyx", 20],
  ["Bharara", "Rose", 20],
  ["Bharara", "Scarlett", 20],
  ["Bharara", "Soleil", 20],
  ["Britney Spears", "Fantasy", 15],
  ["Britney Spears", "Fantasy Anniversary", 15],
  ["Britney Spears", "Fantasy Midnight", 15],
  ["Calvin Klein", "Eternity", 15],
  ["Calvin Klein", "One", 15],
  ["Carolina Herrera", "212 Héroes Forever Young W", 15],
  ["Carolina Herrera", "212 Men Heroes Forever Young", 15],
  ["Carolina Herrera", "212 Men NYC", 15],
  ["Carolina Herrera", "212 VIP Black", 15],
  ["Carolina Herrera", "212 VIP Black I Love NY", 15],
  ["Carolina Herrera", "212 VIP Men", 15],
  ["Carolina Herrera", "212 VIP Rosé", 15],
  ["Carolina Herrera", "212 VIP Rosé NY", 15],
  ["Carolina Herrera", "Bad Boy", 15],
  ["Carolina Herrera", "CH", 15],
  ["Carolina Herrera", "Good Girl", 15],
  ["Carolina Herrera", "Good Girl Blush", 20],
  ["Carolina Herrera", "Good Girl Gold Fantasy", 15],
  ["Carolina Herrera", "Good Girl Fantastic Pink", 20],
  ["Carolina Herrera", "Good Girl Blush Elixir", 20],
  ["Carolina Herrera", "Good Girl Velvet Fatale", 15],
  ["Carolina Herrera", "La Bomba", 20],
  ["Carolina Herrera", "Very Good Girl", 15],
  ["Chanel", "Allure Homme Sport", 15],
  ["Chanel", "Bleu de Chanel", 15],
  ["Chanel", "Chance Eau Tendre", 15],
  ["Chanel", "Chanel No.5", 15],
  ["Chanel", "Coco Mademoiselle", 15],
  ["Christian Dior", "Miss Dior", 20],
  ["Christian Dior", "Sauvage", 18],
  ["Christian Dior", "Sauvage Elixir", 18],
  ["Creed", "Creed Aventus", 15],
  ["Creed", "Creed Silver Mountain Water", 15],
  ["Creed", "Creed Absolu Aventus", 15],
  ["Dolce & Gabbana", "Light Blue Pour Femme", 15],
  ["Dolce & Gabbana", "Light Blue Pour Homme", 15],
  ["Dolce & Gabbana", "Light Blue Love is Love W", 15],
  ["Dumont", "Nitro Red", 20],
  ["Escada", "Fairy Love", 9],
  ["Escada", "Sorbetto Rosso", 15],
  ["Ferrari", "Scuderia Ferrari Red", 15],
  ["French Avenue", "Vulcan Baie", 20],
  ["French Avenue", "Vulcan Feu", 20],
  ["French Avenue", "Vulcan Sable", 20],
  ["Giorgio Armani", "Acqua Di Gio (Normal)", 15],
  ["Giorgio Armani", "Acqua Di Gio Profumo", 15],
  ["Giorgio Armani", "Stronger With You", 20],
  ["Giorgio Armani", "Stronger With You Intensely", 20],
  ["Givenchy", "Pour Homme", 15],
  ["Hugo Boss", "Man", 15],
  ["Hugo Boss", "Intense", 15],
  ["Hugo Boss", "Jeans", 15],
  ["Hugo Boss", "Boss Bottled", 15],
  ["Hugo Boss", "Boss Bottled Infinite", 15],
  ["Hugo Boss", "Boss Bottled Night", 15],
  ["Hugo Boss", "Boss Bottled Marine", 15],
  ["Hugo Boss", "Boss Unlimited", 15],
  ["Hugo Boss", "Boss Bottled Absolu", 15],
  ["Hugo Boss", "Hugo Boss Parfum", 15],
  ["Hugo Boss", "The Scent Woman", 9],
  ["Issey Miyake", "L'eau D'issey pour Homme", 15],
  ["Jean Paul Gaultier", "Gaultier Divine", 20],
  ["Jean Paul Gaultier", "La Belle Paradise Garden", 20],
  ["Jean Paul Gaultier", "Le Male", 20],
  ["Jean Paul Gaultier", "Le Male Aviator", 20],
  ["Jean Paul Gaultier", "Le Male Le Parfum", 20],
  ["Jean Paul Gaultier", "Le Beau", 20],
  ["Jean Paul Gaultier", "Le Beau Le Parfum", 20],
  ["Jean Paul Gaultier", "Le Beau Paradise Garden", 20],
  ["Jean Paul Gaultier", "Le Male Elixir", 20],
  ["Jean Paul Gaultier", "Scandal Pour Femme", 20],
  ["Jean Paul Gaultier", "Scandal Pour Homme", 20],
  ["Jean Paul Gaultier", "Scandal Intense", 20],
  ["Jean Paul Gaultier", "Scandal Le Parfum", 20],
  ["Jean Paul Gaultier", "Ultra Male", 20],
  ["Katy Perry", "Purr", 15],
  ["Katy Perry", "Meow", 15],
  ["Lacoste", "Essential", 15],
  ["Lancôme", "Idôle", 9],
  ["Lancôme", "La Vie Est Belle", 15],
  ["Lancôme", "La Vie Est Belle Elixir", 15],
  ["Lattafa", "Art of Universe", 20],
  ["Lattafa", "Asad Bourbon", 15],
  ["Lattafa", "Asad Elixir", 20],
  ["Lattafa", "Asad (Original)", 15],
  ["Lattafa", "Asad Zanzibar", 15],
  ["Lattafa", "Bade'e Al Oud Amethyst", 20],
  ["Lattafa", "Bade'e Al Oud Honor & Glory", 20],
  ["Lattafa", "Bade'e Al Oud Noble Blush", 20],
  ["Lattafa", "Bade'e Al Oud Oud For Glory", 20],
  ["Lattafa", "Bade'e Al Oud Sublime", 20],
  ["Lattafa", "Eclaire (Original)", 20],
  ["Lattafa", "Eclaire Banoffi", 20],
  ["Lattafa", "Eclaire Pistache", 20],
  ["Lattafa", "Emeer", 20],
  ["Lattafa", "Fakhar Lattafa Men", 20],
  ["Lattafa", "Fakhar Lattafa Women", 20],
  ["Lattafa", "Fakhar Lattafa Platin", 20],
  ["Lattafa", "Fakhar Lattafa Extrait", 20],
  ["Lattafa", "Give Me Gourmand Whipped Pleasure", 22],
  ["Lattafa", "Give Me Gourmand Mallow Madness", 22],
  ["Lattafa", "Give Me Gourmand Choco Overdose", 22],
  ["Lattafa", "Give Me Gourmand Cookie Crave", 22],
  ["Lattafa", "Give Me Gourmand Vanilla Freak", 22],
  ["Lattafa", "Give Me Gourmand Berrey On Top", 22],
  ["Lattafa", "Haya", 20],
  ["Lattafa", "Emaan", 20],
  ["Lattafa", "Sakeena", 20],
  ["Lattafa", "Sehr Lattafa", 20],
  ["Lattafa", "Her Confession", 20],
  ["Lattafa", "His Confession", 20],
  ["Lattafa", "Khamrah", 20],
  ["Lattafa", "Khamrah Dukhan", 20],
  ["Lattafa", "Khamrah Qahwa", 20],
  ["Lattafa", "Khamrah Waha", 20],
  ["Lattafa", "Mayar (Original)", 20],
  ["Lattafa", "Mayar Cherry", 20],
  ["Lattafa", "Mayar Natural Intense", 20],
  ["Lattafa", "Victoria Lattafa", 20],
  ["Lattafa", "Yara", 15],
  ["Lattafa", "Yara Candy", 15],
  ["Lattafa", "Yara Elixir", 20],
  ["Lattafa", "Yara Moi", 15],
  ["Lattafa", "Yara Tous", 15],
  ["Le Labo", "Santal 33", 20],
  ["Marc Jacobs", "Decadence", 9],
  ["Moschino", "Moschino Toy 2 (Blanco)", 15],
  ["Moschino", "Moschino Toy 2 Gum Rosado", 15],
  ["Nautica", "Voyage", 15],
  ["Orientica", "Amber Rouge", 20],
  ["Orientica", "Exclusive Dania", 20],
  ["Orientica", "Noble", 20],
  ["Orientica", "Royal Amber", 20],
  ["Orientica", "Royal Bleu", 20],
  ["Orientica", "Velvet Gold", 20],
  ["Orientica", "Oud Saffron", 20],
  ["Orientica", "Exclusive Azure Fantasy", 20],
  ["Paco Rabanne", "1 Million (Original)", 15],
  ["Paco Rabanne", "1 Million Elixir", 15],
  ["Paco Rabanne", "1 Million Lucky", 15],
  ["Paco Rabanne", "1 Million Royal", 15],
  ["Paco Rabanne", "Lady Million", 15],
  ["Paco Rabanne", "Lady Million Lucky", 15],
  ["Paco Rabanne", "Fame (Original)", 15],
  ["Paco Rabanne", "Fame Intense", 15],
  ["Paco Rabanne", "Fame Parfum", 15],
  ["Paco Rabanne", "Invictus", 15],
  ["Paco Rabanne", "Invictus Ónix", 15],
  ["Paco Rabanne", "Invictus Victory", 15],
  ["Paco Rabanne", "Invictus Victory Elixir", 15],
  ["Paco Rabanne", "Invictus Parfum", 15],
  ["Paco Rabanne", "Invictus Platinum", 15],
  ["Paco Rabanne", "Olympea Parfum", 15],
  ["Paco Rabanne", "Olympea", 15],
  ["Paco Rabanne", "Phantom", 20],
  ["Paco Rabanne", "Phantom Parfum", 20],
  ["Paco Rabanne", "Phantom Intense", 20],
  ["Parfums de Marly", "Layton", 20],
  ["Parfums de Marly", "Delina", 20],
  ["Paris Hilton", "Paris Hilton For Men", 15],
  ["Paris Hilton", "Paris Hilton For Women", 15],
  ["Paris Hilton", "Heiress by Paris Hilton", 15],
  ["Paris Hilton", "Can Can", 15],
  ["Perry Ellis", "360 For Men", 15],
  ["Perry Ellis", "360 Red", 15],
  ["Rasasi", "Hawas for Her", 20],
  ["Rasasi", "Hawas for Him", 20],
  ["Rasasi", "Hawas Ice", 20],
  ["Rasasi", "Hawas Fire", 20],
  ["Rasasi", "Hawas Elixir", 20],
  ["Rasasi", "Hawas Malibu", 20],
  ["Rasasi", "Hawas Black", 20],
  ["Rasasi", "Hawas Kobra", 20],
  ["Rave", "Now Woman Pink", 20],
  ["Saint Laurent", "Yves Saint Laurent", 18],
  ["Emper", "Stallion 53", 15],
  ["Tommy Hilfiger", "Tommy", 15],
  ["Tommy Hilfiger", "Tommy Girl", 15],
  ["Valentino", "Valentino Donna Born In Roma", 20],
  ["Valentino", "Valentino Donna Born In Roma Coral Fantasy", 20],
  ["Valentino", "Valentino Donna Born In Roma Yellow Dream", 20],
  ["Valentino", "Valentino Donna Born In Roma Ivory", 20],
  ["Valentino", "Valentino Uomo", 20],
  ["Valentino", "Valentino Uomo Born In Roma", 20],
  ["Versace", "Eros", 15],
  ["Versace", "Eros Energy", 15],
  ["Versace", "Eros Flame", 15],
  ["Victoria Secret", "Bombshell Intense", 9],
  ["Victorinox", "Swiss Army Classic", 15],
  ["Xerjoff", "Erba Pura", 20],
  ["Xerjoff", "Naxos", 20],
];

const PERFUMES = PERFUMES_RAW.map(([casa, nombre, precioMayor, precioDetal], i) => ({
  id: `p${String(i + 1).padStart(3, "0")}`,
  casa,
  nombre,
  precioMayor,
  precioDetal: precioDetal ?? precioMayor + DETAL_MARKUP,
}));
